version: '3.3'

services:

  db:
    build: ./db # for local dockerfile development, ignored by swarm
    image: trota/gorediscompose_db # pull form docker hub
    #image: 127.0.0.1:5000/gorediscompose_db  # pull from local repo
    #ports:
      #- "6379"
    #container_name: db

  api:
    build: ./api # for local dockerfile development, swarm ignores
    image: trota/gorediscompose_api # pull from docker hub
    #image: 127.0.0.1:5000/gorediscompose_api # pull from local registry
    volumes:
      - /Users/trota/code/go/src/go-redis-compose:/code/go/src/go-redis-compose
    working_dir: /code/go/src/go-redis-compose
    command: go run main.go router.go routes.go models.go db.go handlers.go
    depends_on:
      - db
    secrets:
      - source: api_key
    environment:
      REDIS_URL: db:6379
      CAT_URL: http://thecatapi.com/api/
      CAT_API_KEY_PASSWORD_FILE: /run/secrets/api_key
    ports:
      - "8080:8080"

secrets:
  api_key:
    file: api-key.env
