version: '3.3'

services:

  db:
    build: ./db
    ports:
      - "6379"
    container_name: db

  api:
    build: ./api
    volumes:
      - ./:/code/go/src/go-redis-compose
    working_dir: /code/go/src/go-redis-compose
    command: go run main.go router.go routes.go models.go db.go handlers.go

    depends_on:
      - db

    environment:
      REDIS_URL: db:6379
      CAT_URL: http://thecatapi.com/api/images/get?format=xml&results_per_page=1

    ports:
      - "8080:8080"
