version: '3.3'

services:

  db:
    build: ./db
    ports:
      - "6379"
    container_name: db

  api:
    build: ./api
    volumes:
      - ./:/code/go/src/go-redis-compose
    working_dir: /code/go/src/go-redis-compose
    command: go run main.go router.go routes.go models.go db.go handlers.go
    #command: go build  # exit with code 0

    # command: go run main.go  # can't find router...undefined: NewRouter
    # command: go run go-redis-compose
    # command: go install go-redis-compose
    # command: go run
    #links:
      #- db:db
    #  - db
    depends_on:
      - db

    environment:
      REDIS_URL: db:6379

    ports:
      - "8080:8080"
